const allSeasons = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17];
const items = [
  { id: 'akashia', name: 'Akashia', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/akashia.png?raw=true' },
  { id: 'bebe_zahara_benet', name: 'BeBe Zahara Benet', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/bebe_zahara_benet.png?raw=true' },
  { id: 'jade', name: 'Jade', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jade.png?raw=true' },
  { id: 'nina_flowers', name: 'Nina Flowers', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/nina_flowers.png?raw=true' },
  { id: 'ongina', name: 'Ongina', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/ongina.png?raw=true' },
  { id: 'rebecca_glasscock', name: 'Rebecca Glasscock', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/rebecca_glasscock.png?raw=true' },
  { id: 'shannel', name: 'Shannel', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/shannel.png?raw=true' },
  { id: 'tammie_brown', name: 'Tammie Brown', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/tammie_brown.png?raw=true' },
  { id: 'victoria_porkchop_parker', name: 'Victoria (Porkchop) Parker', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/victoria_porkchop_parker.png?raw=true' },
  { id: 'jessica_wild', name: 'Jessica Wild', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jessica_wild.png?raw=true' },
  { id: 'jujubee', name: 'Jujubee', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jujubee.png?raw=true' },
  { id: 'morgan_mcmichaels', name: 'Morgan McMichaels', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/morgan_mcmichaels.png?raw=true' },
  { id: 'mystique_summers_madison', name: 'Mystique Summers Madison', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/mystique_summers_madison.png?raw=true' },
  { id: 'nicole_paige_brooks', name: 'Nicole Paige Brooks', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/nicole_paige_brooks.png?raw=true' },
  { id: 'pandora_boxx', name: 'Pandora Boxx', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/pandora_boxx.png?raw=true' },
  { id: 'raven', name: 'Raven', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/raven.png?raw=true' },
  { id: 'sahara_davenport', name: 'Sahara Davenport', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/sahara_davenport.png?raw=true' },
  { id: 'shangela', name: 'Shangela', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/shangela.png?raw=true' },
  { id: 'sonique', name: 'Sonique', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/sonique.png?raw=true' },
  { id: 'tatianna', name: 'Tatianna', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/tatianna.png?raw=true' },
  { id: 'tyra_sanchez', name: 'Tyra Sanchez', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/tyra_sanchez.png?raw=true' },
  { id: 'alexis_mateo', name: 'Alexis Mateo', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/alexis_mateo.png?raw=true' },
  { id: 'carmen_carrera', name: 'Carmen Carrera', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/carmen_carrera.png?raw=true' },
  { id: 'delta_work', name: 'Delta Work', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/delta_work.png?raw=true' },
  { id: 'india_ferrah', name: 'India Ferrah', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/india_ferrah.png?raw=true' },
  { id: 'manila_luzon', name: 'Manila Luzon', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/manila_luzon.png?raw=true' },
  { id: 'mariah', name: 'Mariah', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/mariah.png?raw=true' },
  { id: 'mimi_imfurst', name: 'Mimi Imfurst', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/mimi_imfurst.png?raw=true' },
  { id: 'phoenix', name: 'Phoenix', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/phoenix.png?raw=true' },
  { id: 'raja', name: 'Raja', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/raja.png?raw=true' },
  { id: 'stacy_layne_matthews', name: 'Stacy Layne Matthews', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/stacy_layne_matthews.png?raw=true' },
  { id: 'venus_d_lite', name: 'Venus D-Lite', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/venus_d_lite.png?raw=true' },
  { id: 'yara_sofia', name: 'Yara Sofia', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/yara_sofia.png?raw=true' },
  { id: 'alisa_summers', name: 'Alisa Summers', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/alisa_summers.png?raw=true' },
  { id: 'chad_michaels', name: 'Chad Michaels', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/chad_michaels.png?raw=true' },
  { id: 'dida_ritz', name: 'Dida Ritz', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/dida_ritz.png?raw=true' },
  { id: 'jiggly_caliente', name: 'Jiggly Caliente', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jiggly_caliente.png?raw=true' },
  { id: 'kenya_michaels', name: 'Kenya Michaels', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kenya_michaels.png?raw=true' },
  { id: 'lashauwn_beyond', name: 'Lashauwn Beyond', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/lashauwn_beyond.png?raw=true' },
  { id: 'latrice_royale', name: 'Latrice Royale', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/latrice_royale.png?raw=true' },
  { id: 'madame_laqueer', name: 'Madame LaQueer', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/madame_laqueer.png?raw=true' },
  { id: 'milan', name: 'Milan', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/milan.png?raw=true' },
  { id: 'phi_phi_o_hara', name: 'Phi Phi O'Hara', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/phi_phi_o_hara.png?raw=true' },
  { id: 'sharon_needles', name: 'Sharon Needles', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/sharon_needles.png?raw=true' },
  { id: 'the_princess', name: 'The Princess', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/the_princess.png?raw=true' },
  { id: 'willam', name: 'Willam', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/willam.png?raw=true' },
  { id: 'alaska', name: 'Alaska', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/alaska.png?raw=true' },
  { id: 'alyssa_edwards', name: 'Alyssa Edwards', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/alyssa_edwards.png?raw=true' },
  { id: 'coco_montrese', name: 'Coco Montrese', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/coco_montrese.png?raw=true' },
  { id: 'detox', name: 'Detox', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/detox.png?raw=true' },
  { id: 'honey_mahogany', name: 'Honey Mahogany', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/honey_mahogany.png?raw=true' },
  { id: 'ivy_winters', name: 'Ivy Winters', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/ivy_winters.png?raw=true' },
  { id: 'jade_jolie', name: 'Jade Jolie', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jade_jolie.png?raw=true' },
  { id: 'jinkx_monsoon', name: 'Jinkx Monsoon', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jinkx_monsoon.png?raw=true' },
  { id: 'lineysha_sparx', name: 'Lineysha Sparx', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/lineysha_sparx.png?raw=true' },
  { id: 'monica_beverly_hillz', name: 'Monica Beverly Hillz', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/monica_beverly_hillz.png?raw=true' },
  { id: 'penny_tration', name: 'Penny Tration', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/penny_tration.png?raw=true' },
  { id: 'roxxxy_andrews', name: 'Roxxxy Andrews', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/roxxxy_andrews.png?raw=true' },
  { id: 'serena_cha_cha', name: 'Serena Cha Cha', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/serena_cha_cha.png?raw=true' },
  { id: 'vivienne_pinay', name: 'Vivienne Pinay', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/vivienne_pinay.png?raw=true' },
  { id: 'adore_delano', name: 'Adore Delano', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/adore_delano.png?raw=true' },
  { id: 'april_carri_n', name: 'April Carrión', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/april_carri_n.png?raw=true' },
  { id: 'bendelacreme', name: 'BenDeLaCreme', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/bendelacreme.png?raw=true' },
  { id: 'bianca_del_rio', name: 'Bianca Del Rio', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/bianca_del_rio.png?raw=true' },
  { id: 'courtney_act', name: 'Courtney Act', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/courtney_act.png?raw=true' },
  { id: 'darienne_lake', name: 'Darienne Lake', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/darienne_lake.png?raw=true' },
  { id: 'gia_gunn', name: 'Gia Gunn', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/gia_gunn.png?raw=true' },
  { id: 'joslyn_fox', name: 'Joslyn Fox', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/joslyn_fox.png?raw=true' },
  { id: 'kelly_mantle', name: 'Kelly Mantle', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kelly_mantle.png?raw=true' },
  { id: 'laganja_estranja', name: 'Laganja Estranja', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/laganja_estranja.png?raw=true' },
  { id: 'magnolia_crawford', name: 'Magnolia Crawford', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/magnolia_crawford.png?raw=true' },
  { id: 'milk', name: 'Milk', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/milk.png?raw=true' },
  { id: 'trinity_k_bonet', name: 'Trinity K. Bonet', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/trinity_k_bonet.png?raw=true' },
  { id: 'vivacious', name: 'Vivacious', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/vivacious.png?raw=true' },
  { id: 'ginger_minj', name: 'Ginger Minj', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/ginger_minj.png?raw=true' },
  { id: 'jaidynn_diore_fierce', name: 'Jaidynn Diore Fierce', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jaidynn_diore_fierce.png?raw=true' },
  { id: 'jasmine_masters', name: 'Jasmine Masters', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jasmine_masters.png?raw=true' },
  { id: 'kandy_ho', name: 'Kandy Ho', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kandy_ho.png?raw=true' },
  { id: 'katya', name: 'Katya', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/katya.png?raw=true' },
  { id: 'kennedy_davenport', name: 'Kennedy Davenport', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kennedy_davenport.png?raw=true' },
  { id: 'max', name: 'Max', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/max.png?raw=true' },
  { id: 'miss_fame', name: 'Miss Fame', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/miss_fame.png?raw=true' },
  { id: 'mrs_kasha_davis', name: 'Mrs. Kasha Davis', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/mrs_kasha_davis.png?raw=true' },
  { id: 'pearl', name: 'Pearl', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/pearl.png?raw=true' },
  { id: 'sasha_belle', name: 'Sasha Belle', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/sasha_belle.png?raw=true' },
  { id: 'tempest_dujour', name: 'Tempest DuJour', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/tempest_dujour.png?raw=true' },
  { id: 'trixie_mattel', name: 'Trixie Mattel', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/trixie_mattel.png?raw=true' },
  { id: 'violet_chachki', name: 'Violet Chachki', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/violet_chachki.png?raw=true' },
  { id: 'acid_betty', name: 'Acid Betty', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/acid_betty.png?raw=true' },
  { id: 'bob_the_drag_queen', name: 'Bob the Drag Queen', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/bob_the_drag_queen.png?raw=true' },
  { id: 'chi_chi_devayne', name: 'Chi Chi DeVayne', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/chi_chi_devayne.png?raw=true' },
  { id: 'cynthia_lee_fontaine', name: 'Cynthia Lee Fontaine', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/cynthia_lee_fontaine.png?raw=true' },
  { id: 'dax_exclamationpoint', name: 'Dax ExclamationPoint', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/dax_exclamationpoint.png?raw=true' },
  { id: 'derrick_barry', name: 'Derrick Barry', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/derrick_barry.png?raw=true' },
  { id: 'kim_chi', name: 'Kim Chi', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kim_chi.png?raw=true' },
  { id: 'laila_mcqueen', name: 'Laila McQueen', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/laila_mcqueen.png?raw=true' },
  { id: 'naomi_smalls', name: 'Naomi Smalls', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/naomi_smalls.png?raw=true' },
  { id: 'naysha_lopez', name: 'Naysha Lopez', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/naysha_lopez.png?raw=true' },
  { id: 'robbie_turner', name: 'Robbie Turner', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/robbie_turner.png?raw=true' },
  { id: 'thorgy_thor', name: 'Thorgy Thor', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/thorgy_thor.png?raw=true' },
  { id: 'aja', name: 'Aja', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/aja.png?raw=true' },
  { id: 'alexis_michelle', name: 'Alexis Michelle', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/alexis_michelle.png?raw=true' },
  { id: 'charlie_hides', name: 'Charlie Hides', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/charlie_hides.png?raw=true' },
  { id: 'eureka_o_hara', name: 'Eureka O'Hara', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/eureka_o_hara.png?raw=true' },
  { id: 'farrah_moan', name: 'Farrah Moan', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/farrah_moan.png?raw=true' },
  { id: 'jaymes_mansfield', name: 'Jaymes Mansfield', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jaymes_mansfield.png?raw=true' },
  { id: 'kimora_blac', name: 'Kimora Blac', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kimora_blac.png?raw=true' },
  { id: 'nina_bo_nina_brown', name: 'Nina Bo'nina Brown', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/nina_bo_nina_brown.png?raw=true' },
  { id: 'peppermint', name: 'Peppermint', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/peppermint.png?raw=true' },
  { id: 'sasha_velour', name: 'Sasha Velour', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/sasha_velour.png?raw=true' },
  { id: 'shea_coule', name: 'Shea Couleé', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/shea_coule.png?raw=true' },
  { id: 'trinity_taylor', name: 'Trinity Taylor', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/trinity_taylor.png?raw=true' },
  { id: 'valentina', name: 'Valentina', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/valentina.png?raw=true' },
  { id: 'aquaria', name: 'Aquaria', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/aquaria.png?raw=true' },
  { id: 'asia_o_hara', name: 'Asia O'Hara', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/asia_o_hara.png?raw=true' },
  { id: 'blair_st_clair', name: 'Blair St. Clair', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/blair_st_clair.png?raw=true' },
  { id: 'dusty_ray_bottoms', name: 'Dusty Ray Bottoms', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/dusty_ray_bottoms.png?raw=true' },
  { id: 'kalorie_karbdashian_williams', name: 'Kalorie Karbdashian Williams', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kalorie_karbdashian_williams.png?raw=true' },
  { id: 'kameron_michaels', name: 'Kameron Michaels', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kameron_michaels.png?raw=true' },
  { id: 'mayhem_miller', name: 'Mayhem Miller', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/mayhem_miller.png?raw=true' },
  { id: 'miz_cracker', name: 'Miz Cracker', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/miz_cracker.png?raw=true' },
  { id: 'monique_heart', name: 'Monique Heart', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/monique_heart.png?raw=true' },
  { id: 'mon_t_x_change', name: 'Monét X Change', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/mon_t_x_change.png?raw=true' },
  { id: 'the_vixen', name: 'The Vixen', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/the_vixen.png?raw=true' },
  { id: 'vanessa_vanjie_mateo', name: 'Vanessa Vanjie Mateo', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/vanessa_vanjie_mateo.png?raw=true' },
  { id: 'yuhua_hamasaki', name: 'Yuhua Hamasaki', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/yuhua_hamasaki.png?raw=true' },
  { id: 'a_keria_c_davenport', name: 'A'Keria C. Davenport', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/a_keria_c_davenport.png?raw=true' },
  { id: 'ariel_versace', name: 'Ariel Versace', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/ariel_versace.png?raw=true' },
  { id: 'brooke_lynn_hytes', name: 'Brooke Lynn Hytes', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/brooke_lynn_hytes.png?raw=true' },
  { id: 'honey_davenport', name: 'Honey Davenport', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/honey_davenport.png?raw=true' },
  { id: 'kahanna_montrese', name: 'Kahanna Montrese', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kahanna_montrese.png?raw=true' },
  { id: 'mercedes_iman_diamond', name: 'Mercedes Iman Diamond', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/mercedes_iman_diamond.png?raw=true' },
  { id: 'nina_west', name: 'Nina West', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/nina_west.png?raw=true' },
  { id: 'plastique_tiara', name: 'Plastique Tiara', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/plastique_tiara.png?raw=true' },
  { id: 'ra_jah_o_hara', name: 'Ra'Jah O'Hara', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/ra_jah_o_hara.png?raw=true' },
  { id: 'scarlet_envy', name: 'Scarlet Envy', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/scarlet_envy.png?raw=true' },
  { id: 'shuga_cain', name: 'Shuga Cain', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/shuga_cain.png?raw=true' },
  { id: 'silky_nutmeg_ganache', name: 'Silky Nutmeg Ganache', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/silky_nutmeg_ganache.png?raw=true' },
  { id: 'soju', name: 'Soju', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/soju.png?raw=true' },
  { id: 'yvie_oddly', name: 'Yvie Oddly', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/yvie_oddly.png?raw=true' },
  { id: 'aiden_zhane', name: 'Aiden Zhane', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/aiden_zhane.png?raw=true' },
  { id: 'brita', name: 'Brita', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/brita.png?raw=true' },
  { id: 'crystal_methyd', name: 'Crystal Methyd', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/crystal_methyd.png?raw=true' },
  { id: 'dahlia_sin', name: 'Dahlia Sin', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/dahlia_sin.png?raw=true' },
  { id: 'gigi_goode', name: 'Gigi Goode', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/gigi_goode.png?raw=true' },
  { id: 'heidi_n_closet', name: 'Heidi N Closet', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/heidi_n_closet.png?raw=true' },
  { id: 'jackie_cox', name: 'Jackie Cox', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jackie_cox.png?raw=true' },
  { id: 'jaida_essence_hall', name: 'Jaida Essence Hall', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jaida_essence_hall.png?raw=true' },
  { id: 'jan', name: 'Jan', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jan.png?raw=true' },
  { id: 'nicky_doll', name: 'Nicky Doll', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/nicky_doll.png?raw=true' },
  { id: 'rock_m_sakura', name: 'Rock M. Sakura', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/rock_m_sakura.png?raw=true' },
  { id: 'sherry_pie', name: 'Sherry Pie', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/sherry_pie.png?raw=true' },
  { id: 'widow_von_du', name: 'Widow Von'Du', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/widow_von_du.png?raw=true' },
  { id: 'denali', name: 'Denali', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/denali.png?raw=true' },
  { id: 'elliott_with_2_ts', name: 'Elliott with 2 Ts', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/elliott_with_2_ts.png?raw=true' },
  { id: 'gottmik', name: 'Gottmik', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/gottmik.png?raw=true' },
  { id: 'joey_jay', name: 'Joey Jay', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/joey_jay.png?raw=true' },
  { id: 'kahmora_hall', name: 'Kahmora Hall', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kahmora_hall.png?raw=true' },
  { id: 'kandy_muse', name: 'Kandy Muse', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kandy_muse.png?raw=true' },
  { id: 'lala_ri', name: 'LaLa Ri', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/lala_ri.png?raw=true' },
  { id: 'olivia_lux', name: 'Olivia Lux', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/olivia_lux.png?raw=true' },
  { id: 'ros', name: 'Rosé', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/ros.png?raw=true' },
  { id: 'symone', name: 'Symone', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/symone.png?raw=true' },
  { id: 'tamisha_iman', name: 'Tamisha Iman', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/tamisha_iman.png?raw=true' },
  { id: 'tina_burner', name: 'Tina Burner', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/tina_burner.png?raw=true' },
  { id: 'utica_queen', name: 'Utica Queen', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/utica_queen.png?raw=true' },
  { id: 'alyssa_hunter', name: 'Alyssa Hunter', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/alyssa_hunter.png?raw=true' },
  { id: 'angeria_paris_vanmicheals', name: 'Angeria Paris VanMicheals', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/angeria_paris_vanmicheals.png?raw=true' },
  { id: 'bosco', name: 'Bosco', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/bosco.png?raw=true' },
  { id: 'daya_betty', name: 'Daya Betty', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/daya_betty.png?raw=true' },
  { id: 'deja_skye', name: 'DeJa Skye', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/deja_skye.png?raw=true' },
  { id: 'jasmine_kennedie', name: 'Jasmine Kennedie', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jasmine_kennedie.png?raw=true' },
  { id: 'jorgeous', name: 'Jorgeous', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/jorgeous.png?raw=true' },
  { id: 'june_jambalaya', name: 'June Jambalaya', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/june_jambalaya.png?raw=true' },
  { id: 'kerri_colby', name: 'Kerri Colby', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kerri_colby.png?raw=true' },
  { id: 'kornbread_the_snack_jete', name: 'Kornbread (The Snack) Jete', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/kornbread_the_snack_jete.png?raw=true' },
  { id: 'lady_camden', name: 'Lady Camden', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/lady_camden.png?raw=true' },
  { id: 'maddy_morphosis', name: 'Maddy Morphosis', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/maddy_morphosis.png?raw=true' },
  { id: 'orion_story', name: 'Orion Story', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/orion_story.png?raw=true' },
  { id: 'willow_pill', name: 'Willow Pill', image: 'https://github.com/xbianchi/favorite-pick/blob/main/Image/willow_pill.png?raw=true' },
  { id: 'amethyst', name: 'Amethyst', image: 'https://via.placeholder.com/150' },
  { id: 'anetra', name: 'Anetra', image: 'https://via.placeholder.com/150' },
  { id: 'aura_mayari', name: 'Aura Mayari', image: 'https://via.placeholder.com/150' },
  { id: 'irene_dubois', name: 'Irene Dubois', image: 'https://via.placeholder.com/150' },
  { id: 'jax', name: 'Jax', image: 'https://via.placeholder.com/150' },
  { id: 'loosey_laduca', name: 'Loosey LaDuca', image: 'https://via.placeholder.com/150' },
  { id: 'luxx_noir_london', name: 'Luxx Noir London', image: 'https://via.placeholder.com/150' },
  { id: 'malaysia_babydoll_foxx', name: 'Malaysia Babydoll Foxx', image: 'https://via.placeholder.com/150' },
  { id: 'marcia_marcia_marcia', name: 'Marcia Marcia Marcia', image: 'https://via.placeholder.com/150' },
  { id: 'mistress_isabelle_brooks', name: 'Mistress Isabelle Brooks', image: 'https://via.placeholder.com/150' },
  { id: 'princess_poppy', name: 'Princess Poppy', image: 'https://via.placeholder.com/150' },
  { id: 'robin_fierce', name: 'Robin Fierce', image: 'https://via.placeholder.com/150' },
  { id: 'salina_estitties', name: 'Salina EsTitties', image: 'https://via.placeholder.com/150' },
  { id: 'sasha_colby', name: 'Sasha Colby', image: 'https://via.placeholder.com/150' },
  { id: 'spice', name: 'Spice', image: 'https://via.placeholder.com/150' },
  { id: 'sugar', name: 'Sugar', image: 'https://via.placeholder.com/150' },
  { id: 'amanda_tori_meating', name: 'Amanda Tori Meating', image: 'https://via.placeholder.com/150' },
  { id: 'dawn', name: 'Dawn', image: 'https://via.placeholder.com/150' },
  { id: 'geneva_karr', name: 'Geneva Karr', image: 'https://via.placeholder.com/150' },
  { id: 'hershii_liqcour_jet', name: 'Hershii LiqCour-Jeté', image: 'https://via.placeholder.com/150' },
  { id: 'megami', name: 'Megami', image: 'https://via.placeholder.com/150' },
  { id: 'mhi_ya_iman_le_paige', name: 'Mhi'ya Iman Le'Paige', image: 'https://via.placeholder.com/150' },
  { id: 'mirage', name: 'Mirage', image: 'https://via.placeholder.com/150' },
  { id: 'morphine_love_dion', name: 'Morphine Love Dion', image: 'https://via.placeholder.com/150' },
  { id: 'nymphia_wind', name: 'Nymphia Wind', image: 'https://via.placeholder.com/150' },
  { id: 'plane_jane', name: 'Plane Jane', image: 'https://via.placeholder.com/150' },
  { id: 'plasma', name: 'Plasma', image: 'https://via.placeholder.com/150' },
  { id: 'q', name: 'Q', image: 'https://via.placeholder.com/150' },
  { id: 'sapphira_cristal', name: 'Sapphira Cristal', image: 'https://via.placeholder.com/150' },
  { id: 'xunami_muse', name: 'Xunami Muse', image: 'https://via.placeholder.com/150' },
];
const itemSeasons = {
  akashia: 1,
  bebe_zahara_benet: 1,
  jade: 1,
  nina_flowers: 1,
  ongina: 1,
  rebecca_glasscock: 1,
  shannel: 1,
  tammie_brown: 1,
  victoria_porkchop_parker: 1,
  jessica_wild: 2,
  jujubee: 2,
  morgan_mcmichaels: 2,
  mystique_summers_madison: 2,
  nicole_paige_brooks: 2,
  pandora_boxx: 2,
  raven: 2,
  sahara_davenport: 2,
  shangela: 2,
  sonique: 2,
  tatianna: 2,
  tyra_sanchez: 2,
  alexis_mateo: 3,
  carmen_carrera: 3,
  delta_work: 3,
  india_ferrah: 3,
  manila_luzon: 3,
  mariah: 3,
  mimi_imfurst: 3,
  phoenix: 3,
  raja: 3,
  stacy_layne_matthews: 3,
  venus_d_lite: 3,
  yara_sofia: 3,
  alisa_summers: 4,
  chad_michaels: 4,
  dida_ritz: 4,
  jiggly_caliente: 4,
  kenya_michaels: 4,
  lashauwn_beyond: 4,
  latrice_royale: 4,
  madame_laqueer: 4,
  milan: 4,
  phi_phi_o_hara: 4,
  sharon_needles: 4,
  the_princess: 4,
  willam: 4,
  alaska: 5,
  alyssa_edwards: 5,
  coco_montrese: 5,
  detox: 5,
  honey_mahogany: 5,
  ivy_winters: 5,
  jade_jolie: 5,
  jinkx_monsoon: 5,
  lineysha_sparx: 5,
  monica_beverly_hillz: 5,
  penny_tration: 5,
  roxxxy_andrews: 5,
  serena_cha_cha: 5,
  vivienne_pinay: 5,
  adore_delano: 6,
  april_carri_n: 6,
  bendelacreme: 6,
  bianca_del_rio: 6,
  courtney_act: 6,
  darienne_lake: 6,
  gia_gunn: 6,
  joslyn_fox: 6,
  kelly_mantle: 6,
  laganja_estranja: 6,
  magnolia_crawford: 6,
  milk: 6,
  trinity_k_bonet: 6,
  vivacious: 6,
  ginger_minj: 7,
  jaidynn_diore_fierce: 7,
  jasmine_masters: 7,
  kandy_ho: 7,
  katya: 7,
  kennedy_davenport: 7,
  max: 7,
  miss_fame: 7,
  mrs_kasha_davis: 7,
  pearl: 7,
  sasha_belle: 7,
  tempest_dujour: 7,
  trixie_mattel: 7,
  violet_chachki: 7,
  acid_betty: 8,
  bob_the_drag_queen: 8,
  chi_chi_devayne: 8,
  cynthia_lee_fontaine: 8,
  dax_exclamationpoint: 8,
  derrick_barry: 8,
  kim_chi: 8,
  laila_mcqueen: 8,
  naomi_smalls: 8,
  naysha_lopez: 8,
  robbie_turner: 8,
  thorgy_thor: 8,
  aja: 9,
  alexis_michelle: 9,
  charlie_hides: 9,
  eureka_o_hara: 9,
  farrah_moan: 9,
  jaymes_mansfield: 9,
  kimora_blac: 9,
  nina_bo_nina_brown: 9,
  peppermint: 9,
  sasha_velour: 9,
  shea_coule: 9,
  trinity_taylor: 9,
  valentina: 9,
  aquaria: 10,
  asia_o_hara: 10,
  blair_st_clair: 10,
  dusty_ray_bottoms: 10,
  kalorie_karbdashian_williams: 10,
  kameron_michaels: 10,
  mayhem_miller: 10,
  miz_cracker: 10,
  monique_heart: 10,
  mon_t_x_change: 10,
  the_vixen: 10,
  vanessa_vanjie_mateo: 10,
  yuhua_hamasaki: 10,
  a_keria_c_davenport: 11,
  ariel_versace: 11,
  brooke_lynn_hytes: 11,
  honey_davenport: 11,
  kahanna_montrese: 11,
  mercedes_iman_diamond: 11,
  nina_west: 11,
  plastique_tiara: 11,
  ra_jah_o_hara: 11,
  scarlet_envy: 11,
  shuga_cain: 11,
  silky_nutmeg_ganache: 11,
  soju: 11,
  yvie_oddly: 11,
  aiden_zhane: 12,
  brita: 12,
  crystal_methyd: 12,
  dahlia_sin: 12,
  gigi_goode: 12,
  heidi_n_closet: 12,
  jackie_cox: 12,
  jaida_essence_hall: 12,
  jan: 12,
  nicky_doll: 12,
  rock_m_sakura: 12,
  sherry_pie: 12,
  widow_von_du: 12,
  denali: 13,
  elliott_with_2_ts: 13,
  gottmik: 13,
  joey_jay: 13,
  kahmora_hall: 13,
  kandy_muse: 13,
  lala_ri: 13,
  olivia_lux: 13,
  ros: 13,
  symone: 13,
  tamisha_iman: 13,
  tina_burner: 13,
  utica_queen: 13,
  alyssa_hunter: 14,
  angeria_paris_vanmicheals: 14,
  bosco: 14,
  daya_betty: 14,
  deja_skye: 14,
  jasmine_kennedie: 14,
  jorgeous: 14,
  june_jambalaya: 14,
  kerri_colby: 14,
  kornbread_the_snack_jete: 14,
  lady_camden: 14,
  maddy_morphosis: 14,
  orion_story: 14,
  willow_pill: 14,
  amethyst: 15,
  anetra: 15,
  aura_mayari: 15,
  irene_dubois: 15,
  jax: 15,
  loosey_laduca: 15,
  luxx_noir_london: 15,
  malaysia_babydoll_foxx: 15,
  marcia_marcia_marcia: 15,
  mistress_isabelle_brooks: 15,
  princess_poppy: 15,
  robin_fierce: 15,
  salina_estitties: 15,
  sasha_colby: 15,
  spice: 15,
  sugar: 15,
  amanda_tori_meating: 16,
  dawn: 16,
  geneva_karr: 16,
  hershii_liqcour_jet: 16,
  megami: 16,
  mhi_ya_iman_le_paige: 16,
  mirage: 16,
  morphine_love_dion: 16,
  nymphia_wind: 16,
  plane_jane: 16,
  plasma: 16,
  q: 16,
  sapphira_cristal: 16,
  xunami_muse: 16,
};
